[package]
name = "receiver_dec_classic"
version = "0.1.0"
edition = "2024"

[dependencies]


tokio = { version = "1", features = ["full"] }
serde_json = "1.0.150"
serde = { version = "1.0", features = ["derive"] }
ed25519-dalek = { version = "3.0.0", features = ["serde", "rand_core"] }
x25519-dalek = { version = "3.0.0"  }

getrandom = { version = "0.4.3", features = ["sys_rng"] } 

#rand = { version = "0.10.2", features = ["std"] }

core_utils_classic = { path = "../core_utils_classic" }


base65 = { path = "../base65" }
tokio-postgres = { version = "0.7", features = ["with-serde_json-1"] }
chrono = { version = "0.4", features = ["serde"] }
useful_stats = { path = "../../evals/useful_stats" }
