[package]
name = "client_auth_text"
version = "0.1.0"
edition = "2024"

[dependencies]

core_utils_text = { path = "../core_utils_text" }
base65 = { path = "../base65" }

tokio = { version = "1", features = ["full"] }
csv = "1.4"


useful_stats = { path = "../../evals/useful_stats" }

env = { version = "1.0.1" }