[package]
name = "receiver_tokio"
version = "0.1.0"
edition = "2024"

[dependencies]

core_utils_tokio = { path = "../core_utils_tokio" }
lattice-kyber = { version = "0.1", features = ["serde"] }

tokio = { version = "1", features = ["full"] }
serde_json = "1.0.150"
serde = { version = "1.0", features = ["derive"] }

base65 = { path = "../base65" }
tokio-postgres = { version = "0.7", features = ["with-serde_json-1"] }
chrono = { version = "0.4", features = ["serde"] }
