[package]
name = "client_auth_pqc"
version = "0.1.0"
edition = "2024"

[dependencies]

core_utils_pqc = { path = "../core_utils_pqc" }
base65 = { path = "../base65" }
lattice-kyber = { version = "0.1", features = ["getrandom","serde"] }

tokio = { version = "1", features = ["full"] }
csv = "1.4"

useful_stats = { path = "../../evals/useful_stats" }

env = { version = "1.0.1" }


[features]
trace = ["core_utils_pqc/trace"]