[package]
name = "receiver_timer"
version = "0.1.0"
edition = "2024"

[dependencies]


tokio = { version = "1", features = ["full"] }
serde_json = "1.0.150"
serde = { version = "1.0", features = ["derive"] }

#rand = { version = "0.10.2", features = ["std"] }




base65 = { path = "../base65" }

chrono = { version = "0.4", features = ["serde"] }
